/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TournamentsNewRouteImport } from './routes/tournaments.new'
import { Route as MatchesIdRouteImport } from './routes/matches.$id'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as TournamentsIdMatchesRouteImport } from './routes/tournaments.$id.matches'
import { Route as TournamentsIdEditRouteImport } from './routes/tournaments.$id.edit'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TournamentsRoute,
} as any)
const TournamentsNewRoute = TournamentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TournamentsRoute,
} as any)
const MatchesIdRoute = MatchesIdRouteImport.update({
  id: '/matches/$id',
  path: '/matches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdMatchesRoute = TournamentsIdMatchesRouteImport.update({
  id: '/$id/matches',
  path: '/$id/matches',
  getParentRoute: () => TournamentsRoute,
} as any)
const TournamentsIdEditRoute = TournamentsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => TournamentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/matches/$id': typeof MatchesIdRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/tournaments/$id/edit': typeof TournamentsIdEditRoute
  '/tournaments/$id/matches': typeof TournamentsIdMatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/join/$token': typeof JoinTokenRoute
  '/matches/$id': typeof MatchesIdRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/tournaments/$id/edit': typeof TournamentsIdEditRoute
  '/tournaments/$id/matches': typeof TournamentsIdMatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/matches/$id': typeof MatchesIdRoute
  '/tournaments/new': typeof TournamentsNewRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/tournaments/$id/edit': typeof TournamentsIdEditRoute
  '/tournaments/$id/matches': typeof TournamentsIdMatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tournaments'
    | '/join/$token'
    | '/matches/$id'
    | '/tournaments/new'
    | '/tournaments/'
    | '/tournaments/$id/edit'
    | '/tournaments/$id/matches'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/join/$token'
    | '/matches/$id'
    | '/tournaments/new'
    | '/tournaments'
    | '/tournaments/$id/edit'
    | '/tournaments/$id/matches'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/tournaments'
    | '/join/$token'
    | '/matches/$id'
    | '/tournaments/new'
    | '/tournaments/'
    | '/tournaments/$id/edit'
    | '/tournaments/$id/matches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
  MatchesIdRoute: typeof MatchesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/tournaments/new': {
      id: '/tournaments/new'
      path: '/new'
      fullPath: '/tournaments/new'
      preLoaderRoute: typeof TournamentsNewRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/matches/$id': {
      id: '/matches/$id'
      path: '/matches/$id'
      fullPath: '/matches/$id'
      preLoaderRoute: typeof MatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/matches': {
      id: '/tournaments/$id/matches'
      path: '/$id/matches'
      fullPath: '/tournaments/$id/matches'
      preLoaderRoute: typeof TournamentsIdMatchesRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/tournaments/$id/edit': {
      id: '/tournaments/$id/edit'
      path: '/$id/edit'
      fullPath: '/tournaments/$id/edit'
      preLoaderRoute: typeof TournamentsIdEditRouteImport
      parentRoute: typeof TournamentsRoute
    }
  }
}

interface TournamentsRouteChildren {
  TournamentsNewRoute: typeof TournamentsNewRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  TournamentsIdEditRoute: typeof TournamentsIdEditRoute
  TournamentsIdMatchesRoute: typeof TournamentsIdMatchesRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsNewRoute: TournamentsNewRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  TournamentsIdEditRoute: TournamentsIdEditRoute,
  TournamentsIdMatchesRoute: TournamentsIdMatchesRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
  MatchesIdRoute: MatchesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
