/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorneiosRouteImport } from './routes/torneios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TorneiosIndexRouteImport } from './routes/torneios.index'
import { Route as TorneiosNewRouteImport } from './routes/torneios.new'
import { Route as TorneiosIdRouteImport } from './routes/torneios/$id'
import { Route as PartidasIdRouteImport } from './routes/partidas.$id'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as TorneiosIdSettingsRouteImport } from './routes/torneios/$id.settings'
import { Route as TorneiosIdOverviewRouteImport } from './routes/torneios/$id.overview'
import { Route as TorneiosIdMatchesRouteImport } from './routes/torneios.$id.matches'
import { Route as TorneiosIdEditRouteImport } from './routes/torneios.$id.edit'

const TorneiosRoute = TorneiosRouteImport.update({
  id: '/torneios',
  path: '/torneios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneiosIndexRoute = TorneiosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TorneiosRoute,
} as any)
const TorneiosNewRoute = TorneiosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TorneiosRoute,
} as any)
const TorneiosIdRoute = TorneiosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TorneiosRoute,
} as any)
const PartidasIdRoute = PartidasIdRouteImport.update({
  id: '/partidas/$id',
  path: '/partidas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneiosIdSettingsRoute = TorneiosIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TorneiosIdRoute,
} as any)
const TorneiosIdOverviewRoute = TorneiosIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => TorneiosIdRoute,
} as any)
const TorneiosIdMatchesRoute = TorneiosIdMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => TorneiosIdRoute,
} as any)
const TorneiosIdEditRoute = TorneiosIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TorneiosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/torneios': typeof TorneiosRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/torneios/$id': typeof TorneiosIdRouteWithChildren
  '/torneios/new': typeof TorneiosNewRoute
  '/torneios/': typeof TorneiosIndexRoute
  '/torneios/$id/edit': typeof TorneiosIdEditRoute
  '/torneios/$id/matches': typeof TorneiosIdMatchesRoute
  '/torneios/$id/overview': typeof TorneiosIdOverviewRoute
  '/torneios/$id/settings': typeof TorneiosIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/join/$token': typeof JoinTokenRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/torneios/$id': typeof TorneiosIdRouteWithChildren
  '/torneios/new': typeof TorneiosNewRoute
  '/torneios': typeof TorneiosIndexRoute
  '/torneios/$id/edit': typeof TorneiosIdEditRoute
  '/torneios/$id/matches': typeof TorneiosIdMatchesRoute
  '/torneios/$id/overview': typeof TorneiosIdOverviewRoute
  '/torneios/$id/settings': typeof TorneiosIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/torneios': typeof TorneiosRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/partidas/$id': typeof PartidasIdRoute
  '/torneios/$id': typeof TorneiosIdRouteWithChildren
  '/torneios/new': typeof TorneiosNewRoute
  '/torneios/': typeof TorneiosIndexRoute
  '/torneios/$id/edit': typeof TorneiosIdEditRoute
  '/torneios/$id/matches': typeof TorneiosIdMatchesRoute
  '/torneios/$id/overview': typeof TorneiosIdOverviewRoute
  '/torneios/$id/settings': typeof TorneiosIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/torneios'
    | '/join/$token'
    | '/partidas/$id'
    | '/torneios/$id'
    | '/torneios/new'
    | '/torneios/'
    | '/torneios/$id/edit'
    | '/torneios/$id/matches'
    | '/torneios/$id/overview'
    | '/torneios/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/join/$token'
    | '/partidas/$id'
    | '/torneios/$id'
    | '/torneios/new'
    | '/torneios'
    | '/torneios/$id/edit'
    | '/torneios/$id/matches'
    | '/torneios/$id/overview'
    | '/torneios/$id/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/torneios'
    | '/join/$token'
    | '/partidas/$id'
    | '/torneios/$id'
    | '/torneios/new'
    | '/torneios/'
    | '/torneios/$id/edit'
    | '/torneios/$id/matches'
    | '/torneios/$id/overview'
    | '/torneios/$id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TorneiosRoute: typeof TorneiosRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
  PartidasIdRoute: typeof PartidasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torneios': {
      id: '/torneios'
      path: '/torneios'
      fullPath: '/torneios'
      preLoaderRoute: typeof TorneiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneios/': {
      id: '/torneios/'
      path: '/'
      fullPath: '/torneios/'
      preLoaderRoute: typeof TorneiosIndexRouteImport
      parentRoute: typeof TorneiosRoute
    }
    '/torneios/new': {
      id: '/torneios/new'
      path: '/new'
      fullPath: '/torneios/new'
      preLoaderRoute: typeof TorneiosNewRouteImport
      parentRoute: typeof TorneiosRoute
    }
    '/torneios/$id': {
      id: '/torneios/$id'
      path: '/$id'
      fullPath: '/torneios/$id'
      preLoaderRoute: typeof TorneiosIdRouteImport
      parentRoute: typeof TorneiosRoute
    }
    '/partidas/$id': {
      id: '/partidas/$id'
      path: '/partidas/$id'
      fullPath: '/partidas/$id'
      preLoaderRoute: typeof PartidasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneios/$id/settings': {
      id: '/torneios/$id/settings'
      path: '/settings'
      fullPath: '/torneios/$id/settings'
      preLoaderRoute: typeof TorneiosIdSettingsRouteImport
      parentRoute: typeof TorneiosIdRoute
    }
    '/torneios/$id/overview': {
      id: '/torneios/$id/overview'
      path: '/overview'
      fullPath: '/torneios/$id/overview'
      preLoaderRoute: typeof TorneiosIdOverviewRouteImport
      parentRoute: typeof TorneiosIdRoute
    }
    '/torneios/$id/matches': {
      id: '/torneios/$id/matches'
      path: '/matches'
      fullPath: '/torneios/$id/matches'
      preLoaderRoute: typeof TorneiosIdMatchesRouteImport
      parentRoute: typeof TorneiosIdRoute
    }
    '/torneios/$id/edit': {
      id: '/torneios/$id/edit'
      path: '/edit'
      fullPath: '/torneios/$id/edit'
      preLoaderRoute: typeof TorneiosIdEditRouteImport
      parentRoute: typeof TorneiosIdRoute
    }
  }
}

interface TorneiosIdRouteChildren {
  TorneiosIdEditRoute: typeof TorneiosIdEditRoute
  TorneiosIdMatchesRoute: typeof TorneiosIdMatchesRoute
  TorneiosIdOverviewRoute: typeof TorneiosIdOverviewRoute
  TorneiosIdSettingsRoute: typeof TorneiosIdSettingsRoute
}

const TorneiosIdRouteChildren: TorneiosIdRouteChildren = {
  TorneiosIdEditRoute: TorneiosIdEditRoute,
  TorneiosIdMatchesRoute: TorneiosIdMatchesRoute,
  TorneiosIdOverviewRoute: TorneiosIdOverviewRoute,
  TorneiosIdSettingsRoute: TorneiosIdSettingsRoute,
}

const TorneiosIdRouteWithChildren = TorneiosIdRoute._addFileChildren(
  TorneiosIdRouteChildren,
)

interface TorneiosRouteChildren {
  TorneiosIdRoute: typeof TorneiosIdRouteWithChildren
  TorneiosNewRoute: typeof TorneiosNewRoute
  TorneiosIndexRoute: typeof TorneiosIndexRoute
}

const TorneiosRouteChildren: TorneiosRouteChildren = {
  TorneiosIdRoute: TorneiosIdRouteWithChildren,
  TorneiosNewRoute: TorneiosNewRoute,
  TorneiosIndexRoute: TorneiosIndexRoute,
}

const TorneiosRouteWithChildren = TorneiosRoute._addFileChildren(
  TorneiosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TorneiosRoute: TorneiosRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
  PartidasIdRoute: PartidasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
